#!/bin/bash

## Bash settings
set -uo pipefail

## Script globals
script_file=$(readlink -f "${BASH_SOURCE[0]}"); export CURRENT_PARENT_BASH_SCRIPT_FILE="$script_file"
script_dir=$(dirname "$script_file")
script_name=$(basename "$script_file")
script_args=("$@")

## Script imports
lib_dir="${script_dir}/../lib"
bash_functions_script="${lib_dir}/bash_script_func.sh"

## Source imports
source "$bash_functions_script"


## Arguments
dst_shp=''
src_layer_arr=()
json=false
dryrun=false

## Custom globals


## Script usage
read -r -d '' script_usage << EOM
Usage: ${script_name} [--dryrun] DST_SHP SRC_LAYER...
EOM
if (( $# < 1 )); then
    echo_e -e "$script_usage"
    exit_script_with_status 1
fi


## Parse arguments
set +u
while (( $# > 0 )); do
    arg="$1"

    if [ "$(string_startswith "$arg" '-')" = false ]; then
        if [ -z "$dst_shp" ]; then
            dst_shp="$arg"
        else
            src_layer_arr+=( "$arg" )
        fi

    else
        arg_opt="$(string_lstrip "$arg" '-')"
        arg_opt_nargs=''
        if [ "$(string_contains "$arg_opt" '=')" = true ]; then
            arg_val=$(printf '%s' "${arg_opt#*=}" | sed -r -e "s|^['\"]+||" -e "s|['\"]+$||")
            arg_opt="${arg_opt%%=*}"
            arg_opt_nargs_do_shift=false
        else
            arg_val="$2"
            arg_opt_nargs_do_shift=true
        fi
        arg_val_can_start_with_dash=false

        if [ "$arg_opt" = 'h' ] || [ "$arg_opt" = 'help' ]; then
            arg_opt_nargs=0
            echo "$script_usage"
            exit 0

        elif [ "$arg_opt" = 'j' ] || [ "$arg_opt" = 'json' ]; then
            arg_opt_nargs=0
            json=true

        elif [ "$arg_opt" = 'dryrun' ]; then
            arg_opt_nargs=0
            dryrun=true

        else
            echo_e "Unexpected argument: ${arg}"
            exit_script_with_status 1
        fi

        if [ -z "$arg_opt_nargs" ]; then
            echo_e "Developer error! "'$arg_opt_nargs'" was not set for argument: ${arg}"
            exit_script_with_status 1
        fi

        if [ "$arg_opt_nargs_do_shift" = true ] && (( arg_opt_nargs >= 1 )); then
            for arg_num in $(seq 1 $arg_opt_nargs); do
                shift
                arg_val="$1"
                if [ -z "$arg_val" ]; then
                    echo_e "Missing expected value (#${arg_num}) for argument: ${arg}"
                    exit_script_with_status 1
                elif [ "$arg_val_can_start_with_dash" = false ] && [ "$(string_startswith "$arg_val" '-')" = true ]; then
                    echo_e "Unexpected argument value: ${arg} ${arg_val}"
                    exit_script_with_status 1
                fi
            done
        fi
    fi

    shift
done
set -u


## Validate arguments

if [ -z "$dst_shp" ] || (( ${#src_layer_arr[@]} == 0 )); then
    echo_e "Both DST_SHP and SRC_LAYER arguments must be provided"
    exit_script_with_status 1
fi
src_layer_dne=false
for src_layer in "${src_layer_arr[@]}"; do
    if [ ! -e "$src_layer" ]; then
        echo_e "SRC_LAYER does not exist: ${src_layer}"
        src_layer_dne=true
    fi
done
if [ "$src_layer_dne" = true ]; then
    exit_script_with_status 1
fi


## Main program

if [ "$json" = true ]; then
    cmd="ogrmerge.py -single -o ${dst_shp} ${src_layer_arr[*]} -src_layer_field_content {DS_BASENAME}"
else
    for src_layer_idx in "${!src_layer_arr[@]}"; do
        src_layer="${src_layer_arr[$src_layer_idx]}"
        if (( src_layer_idx == 0 )); then
            echo "Creating output shapefile '${dst_shp}' with source layer: ${src_layer}"
            cmd="ogr2ogr -f 'ESRI Shapefile' ${dst_shp} ${src_layer}"
        else
            echo "Appending source layer: ${src_layer}"
            cmd="ogr2ogr -f 'ESRI Shapefile' -update -append ${dst_shp} ${src_layer}"
        fi
    done
fi

echo "$cmd"
if [ "$dryrun" = false ]; then
    eval "$cmd"
    if [ -f "$dst_shp" ]; then
        echo "Generated output layer file: ${dst_shp}"
    else
        echo "Failed to generate output layer file: ${dst_shp}"
    fi
fi
